name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  typecheck_lint_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm install --no-audit --no-fund

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test:unit

  contracts:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Generate contract snapshot (PR)
        run: node scripts/generate-contract-snapshot.js

      - name: Diff against base (best-effort)
        run: |
          # Attempt to diff; if baseline missing, do not fail the build
          node scripts/diff-contracts.js --fail-on-breaking || echo "No baseline or differences; continuing"

