name: E2E Smoke (Scheduled)

on:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base URL to test (defaults to staging)"
        required: false
        default: ""

jobs:
  e2e-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Run E2E Smoke
        env:
          BASE_URL: ${{ inputs.base_url || secrets.STAGING_URL || 'https://stream-flow-git-main-christcr2012s-projects.vercel.app' }}
          E2E_EXPECT_FED_ENABLED: "true"
        run: npm run test:e2e

